### ISSUE TITLE
Text UI Testing Issue

### ISSUE THREAD

**Issue by mudkip8** [nus-cs2113-AY2122S1/forum#35]
I am facing an issue with the Text UI Testing part of the IP. The .bat file cannot read more than 1 line of input into the program, and returns the following error:

`Exception in thread "main" java.util.NoSuchElementException: No line found`
        `at java.base/java.util.Scanner.nextLine(Scanner.java:1651)`
        `at Duke.main(Duke.java:11)`

The relevant code segment is below:
```java 
do {
    Scanner line = new Scanner(System.in);
    String[] input = line.nextLine().split(" ", 2);
    switch (input[0]) {
    case "bye":
        taskManager.exitMessage();
        isExit = true;
        break;
     //remainder of the input cases below
     }
} while (!isExit);
```
Input.txt is as below
`todo fly`
`deadline fall /by 2pm` 
`bye` 

The ACTUAL.TXT produced stops after the first input line, which is "todo fly". Am I using scanner wrong? Thanks in advance

**Comment by mudkip8** [comment]
Hello All who have taken time to read.

It turns out that putting the Scanner creation line within the loop was causing the problem. The solution was to move it out of the loop. I hope no one else spends 3 hours trying to deal with this too 👍 .

Thanks!
